### PR TITLE
Add Animations Component

### PR DESCRIPTION
**Pull request by Mike-MF**
**When merged this pull request will:**
- Increases switch to handgun speed.
- Increases swim speed to more bearable and realistic.
- Increases ladder climbing speed.

### CODE REVIEW

**Comment by jonpas** [comment]
Not sure I am a fan of this. Doesn't it change the play too significantly?

**Comment by Mike-MF** [comment]
Not as much as you'd think.

- The swimming change is because the default is ridiculously slow, nobody in moderately good physical shape would struggle to swim much faster than you can in Arma, even with the gear.
- Ladder change was also another one, ridiculously slow for the sake of it, this isn't too fast and we don't climb them all that often.
- Handgun switching is just fast enough to make it viable now which makes sense given how often you see shooters doing it.

**Comment by jonpas** [comment]
- Swimming with our usual full gear is often impossible, not just slow.
- Ladder sure.
- Competitive shooters, not soldiers.

**Comment by Mike-MF** [comment]
Then it would make sense to swim faster, we actively avoid it because it takes an eternity to move 10m, it's just opening up possibilities for us.

True, but we aren't soldiers ;)

**Pull request merged**
