### PR TITLE
Markers - Sharpen Markers

### PR DESCRIPTION
**Pull request by Mike-MF**
> JJ wanted me to sharpen the map markers up to better match the vanilla markers.

### CODE REVIEW

**Comment by jonpas** [comment]
@Mike-MF Can you get a screenshot of one of those markers next to a vanilla "Objective" marker? That's what I was using as comparison.

**Comment by Mike-MF** [comment]
> @Mike-MF Can you get a screenshot of one of those markers next to a vanilla "Objective" marker? That's what I was using as comparison.
Untitled

**Comment by jonpas** [comment]
Looks much better, but why do some markers have gaps in the circle? :thinking:

**Comment by Mike-MF** [comment]
They're meant to be "drawn" so imperfect. I'm left handed and can't draw a circle for shit so these are good in comparison :D

**Comment by jonpas** [comment]
Not gaps like that, but like artifacts, missing pixels.

I like the "hand-drawn" aspect. The whole reason I even mentioned this was that the original custom ones were too much "hand-drawn" in comparison to vanilla, and they didn't fit when used together. :D

**Review by jonpas — APPROVED** [review]

**Pull request merged**
