### PR TITLE
Animations - Remove sitting smoking idle animation

### PR DESCRIPTION
**Pull request by Mike-MF**
**When merged this pull request will:**
- Looks like you're sniffing your hand and it drives me nuts.

### CODE REVIEW

**Comment by jonpas** [comment]
Put it into ACE noidle?

**Comment by Mike-MF** [comment]
Isn't that purely for removing all the idling animations? This is just 1 of 3

**Comment by jonpas** [comment]
Yes, but if we see this aniamtion, ACE doesn't remove them, but it should, no?

**Comment by Mike-MF** [comment]
From what I can see ACE just removes the standing Idling animations, but they're so old they may not actually be used animations anymore.

**Pull request merged**
